### ISSUE TITLE
Option to specify check severity

### ISSUE THREAD

**Issue by the-tatanka** [bridgecrewio/bridgecrew-action#28]
There is an option to check individual checks via their identifiers.
It would also be good if you could select the checks by their severity.

For example only "--check HIGH" as in https://github.com/bridgecrewio/checkov with "checkov -d . --check MEDIUM".

My current config is:
```
- name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          quiet: true 
          soft_fail: false 
          framework: all
          output_format: sarif 
          download_external_modules: true
          log_level: WARNING 
          check: LOW # Results in - no checks applied
```
