### ISSUE TITLE
Action passes with errors when soft_fail false

### ISSUE THREAD

**Issue by blackdenc** [bridgecrewio/bridgecrew-action#9]
Using this action as configured below, the checks pass even though errors are detected. Soft-fail is not configured, and no rules are skipped. 

![image](https://user-images.githubusercontent.com/51961064/105209335-b7259100-5b17-11eb-8a66-a5a37751217e.png)

```
---
  name: Run Bridgecrew
  on:
    push:
      branches-ignore:
        - 'master'
  
  jobs:
    build:
      name: Check chopd3b IaC rules
      runs-on: ubuntu-latest
      steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - name: Checkout codebase
          uses: actions/checkout@v2
        
        - name: Run Bridgecrew
          id: Bridgecrew
          uses: bridgecrewio/bridgecrew-action@master
          with:
            api-key: ${{ secrets.BRIDGECREW_API_KEY }}
```
